//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjNewPet.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbNewPetEntities : DbContext
    {
        public dbNewPetEntities()
            : base("name=dbNewPetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tActivity> tActivities { get; set; }
        public virtual DbSet<tAdoptMessage> tAdoptMessages { get; set; }
        public virtual DbSet<tAuthority> tAuthorities { get; set; }
        public virtual DbSet<tBreed> tBreeds { get; set; }
        public virtual DbSet<tCategory> tCategories { get; set; }
        public virtual DbSet<tCity> tCities { get; set; }
        public virtual DbSet<tComment> tComments { get; set; }
        public virtual DbSet<tCurse> tCurses { get; set; }
        public virtual DbSet<tDiscussion> tDiscussions { get; set; }
        public virtual DbSet<tDiscussionClass> tDiscussionClasses { get; set; }
        public virtual DbSet<tEmployee> tEmployees { get; set; }
        public virtual DbSet<tFavorite> tFavorites { get; set; }
        public virtual DbSet<tFoundPet> tFoundPets { get; set; }
        public virtual DbSet<tLike> tLikes { get; set; }
        public virtual DbSet<tLogInWay> tLogInWays { get; set; }
        public virtual DbSet<tLostPet> tLostPets { get; set; }
        public virtual DbSet<tMember> tMembers { get; set; }
        public virtual DbSet<tOrder_Detail> tOrder_Detail { get; set; }
        public virtual DbSet<tOrder> tOrders { get; set; }
        public virtual DbSet<tPayWay> tPayWays { get; set; }
        public virtual DbSet<tPetClass> tPetClasses { get; set; }
        public virtual DbSet<tPetMember> tPetMembers { get; set; }
        public virtual DbSet<tProduct> tProducts { get; set; }
        public virtual DbSet<tPurchase> tPurchases { get; set; }
        public virtual DbSet<tPurchase_Detials> tPurchase_Detials { get; set; }
        public virtual DbSet<tPurchaseShoppingCart> tPurchaseShoppingCarts { get; set; }
        public virtual DbSet<tRegion> tRegions { get; set; }
        public virtual DbSet<tReply> tReplies { get; set; }
        public virtual DbSet<tReport> tReports { get; set; }
        public virtual DbSet<tShipVia> tShipVias { get; set; }
        public virtual DbSet<tShoppingCart> tShoppingCarts { get; set; }
        public virtual DbSet<tSupplier> tSuppliers { get; set; }
    }
}
