//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjNewPet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tOrder()
        {
            this.tOrder_Detail = new HashSet<tOrder_Detail>();
        }
    
        public int fOrderID { get; set; }
        public int fMemberID { get; set; }
        public Nullable<System.DateTime> fOrderDate { get; set; }
        public Nullable<System.DateTime> fShipOutDate { get; set; }
        public string fReceiverName { get; set; }
        public string fReceiverPhone { get; set; }
        public int fCityID { get; set; }
        public int fRegionID { get; set; }
        public string fAddressDetail { get; set; }
        public string fReceiverMail { get; set; }
        public int fPayWayID { get; set; }
        public string fStatus { get; set; }
    
        public virtual tCity tCity { get; set; }
        public virtual tMember tMember { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tOrder_Detail> tOrder_Detail { get; set; }
        public virtual tPayWay tPayWay { get; set; }
        public virtual tRegion tRegion { get; set; }
    }
}
