//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjNewPet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tProduct()
        {
            this.tOrder_Detail = new HashSet<tOrder_Detail>();
            this.tPurchase_Detials = new HashSet<tPurchase_Detials>();
            this.tPurchaseShoppingCarts = new HashSet<tPurchaseShoppingCart>();
            this.tShoppingCarts = new HashSet<tShoppingCart>();
        }
    
        public int fProductID { get; set; }
        public string fName { get; set; }
        public string fPic { get; set; }
        public int fCategoryID { get; set; }
        public decimal fUnitPrice { get; set; }
        public int fUnitOnOrder { get; set; }
        public int fUnitInStock { get; set; }
        public Nullable<System.DateTime> fOnShelfDate { get; set; }
        public int fSupplierID { get; set; }
        public int fSafeStock { get; set; }
        public string fDescription { get; set; }
    
        public virtual tCategory tCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tOrder_Detail> tOrder_Detail { get; set; }
        public virtual tSupplier tSupplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tPurchase_Detials> tPurchase_Detials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tPurchaseShoppingCart> tPurchaseShoppingCarts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tShoppingCart> tShoppingCarts { get; set; }
    }
}
