//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjNewPet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tSupplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tSupplier()
        {
            this.tProducts = new HashSet<tProduct>();
            this.tPurchase_Detials = new HashSet<tPurchase_Detials>();
            this.tPurchaseShoppingCarts = new HashSet<tPurchaseShoppingCart>();
        }
    
        public int fSupplierID { get; set; }
        public string fName { get; set; }
        public string fContactName { get; set; }
        public string fAddress { get; set; }
        public int fCityID { get; set; }
        public int fRegionID { get; set; }
        public string fPhone { get; set; }
    
        public virtual tCity tCity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tProduct> tProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tPurchase_Detials> tPurchase_Detials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tPurchaseShoppingCart> tPurchaseShoppingCarts { get; set; }
        public virtual tRegion tRegion { get; set; }
    }
}
